README.md
src/main/scala/in/rcard/raise4s/Builders.scala
src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/BuildersSpec.scala
src/test/scala/in/rcard/raise4s/FoldSpec.scala
src/test/scala/in/rcard/raise4s/RaiseSpec.scala

Added a scope 'Raise' for all the top level functions

---

README.md
src/main/scala/in/rcard/raise4s/Builders.scala
src/test/scala/in/rcard/raise4s/BuildersSpec.scala

4 add a method to lift a value to raise context

---

src/main/scala/in/rcard/raise4s/Builders.scala
src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/RaiseSpec.scala

Deprecated functions without a scope

---

README.md
src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/FoldSpec.scala

Added typed error accumulation

---

README.md
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/RaiseSpec.scala

Added the 'catching' function as an extension method.

---

README.md
src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/BuildersSpec.scala
src/test/scala/in/rcard/raise4s/RaiseSpec.scala

12 currying dsl functions

---

README.md
src/main/scala/in/rcard/raise4s/Bind.scala
src/main/scala/in/rcard/raise4s/Builders.scala
src/test/scala/in/rcard/raise4s/BindTest.scala
src/test/scala/in/rcard/raise4s/BuildersSpec.scala

Rename the `bind()` method into `value`

---

README.md
src/main/scala/in/rcard/raise4s/Bind.scala
src/test/scala/in/rcard/raise4s/BindTest.scala

Added the 'value' function for the List[Either[E, A]] type

---

src/main/scala/in/rcard/raise4s/Builders.scala
src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala

inlined Raise functions

---

README.md
src/main/scala/in/rcard/raise4s/Raise.scala
src/main/scala/in/rcard/raise4s/Runtime.scala
src/test/scala/in/rcard/raise4s/RuntimeSpec.scala

Create a run function returning a union type E | A

---

src/main/scala/in/rcard/raise4s/Fold.scala
src/main/scala/in/rcard/raise4s/Raise.scala
src/test/scala/in/rcard/raise4s/FoldSpec.scala

Added the `mapOrAccumulate` variant that accumulates on a custom type

---

core/src/main/scala/in/rcard/raise4s/Bind.scala
core/src/main/scala/in/rcard/raise4s/Builders.scala
core/src/main/scala/in/rcard/raise4s/Fold.scala
core/src/main/scala/in/rcard/raise4s/Raise.scala
core/src/main/scala/in/rcard/raise4s/Runtime.scala
core/src/test/scala/in/rcard/raise4s/BindSpec.scala

Fixed inline functions

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsRaiseSpec.scala

Added a variation of the `mapOrAccumulate` function using the `cats.data.NonEmptyList`

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsRaiseSpec.scala

Added variations of the `zipOrAccumulate` function using the `cats.data.NonEmptyList`

---

core/src/main/scala/in/rcard/raise4s/Builders.scala

Removed deprecated functions

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsBind.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsBindSpec.scala

Added the conversion from 'Validated' type to `Raise` type

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsRaiseSpec.scala

Added builders 'validated', 'validatedNec', and 'validatedNel'

---

core/src/main/scala/in/rcard/raise4s/Raise.scala

Fixed documentation

---

core/src/main/scala/in/rcard/raise4s/Raise.scala

chore(67): Added the type alias RaiseAcc

---

cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
core/src/main/scala/in/rcard/raise4s/Fold.scala

chore(66): Added the type alias RaiseNel

---

core/src/main/scala/in/rcard/raise4s/Strategies.scala
core/src/test/scala/in/rcard/raise4s/StrategiesSpec.scala

chore(70): Added the 'anyRaised' type alias

---

README.md
core/src/main/scala/in/rcard/raise4s/Raise.scala
core/src/main/scala/in/rcard/raise4s/Strategies.scala
core/src/test/scala/in/rcard/raise4s/RaiseSpec.scala

Added a recovery stategy for raised errors

---

README.md
core/src/main/scala/in/rcard/raise4s/Raise.scala
core/src/test/scala/in/rcard/raise4s/RaiseSpec.scala

Added the 'withDefault' function

---

README.md

docs(91): Fixed documentation

---

README.md
core/src/main/scala/in/rcard/raise4s/Fold.scala
core/src/test/scala/in/rcard/raise4s/FoldSpec.scala

feat(96): Added `values` function for `Iterable[A]` type

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsBind.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsBindSpec.scala

feat(98): Added `values` function accumulating errors in a `NonEmptyList[E]` for `Iterable[A]` type

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsBind.scala
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsBindSpec.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsRaiseSpec.scala

feat(100): Added `values` function accumulating errors in a `NonEmptyList[E]` for `NonEmptyList[A]` type

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsBind.scala
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsBindSpec.scala

feat(99): Added `combineErrorsS` function

---

cats-raise4s/README.md
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsBind.scala
cats-raise4s/src/main/scala/in/rcard/raise4s/cats/CatsRaise.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsBindSpec.scala
cats-raise4s/src/test/scala/in/rcard/raise4s/cats/CatsRaiseSpec.scala

feat(101): Added `combineErrorsS` function for NonEmptyList[A]

---

README.md
core/src/main/scala/in/rcard/raise4s/Accumulation.scala
core/src/test/scala/in/rcard/raise4s/AccumulationSpec.scala

Add a more usable API for error accumulation

---

README.md
core/src/main/scala/in/rcard/raise4s/Accumulation.scala
core/src/test/scala/in/rcard/raise4s/AccumulationSpec.scala

Let the `accumulate` mimic the `mapOrAccumulate` behavior

---

README.md
core/src/main/scala/in/rcard/raise4s/Raise.scala
core/src/main/scala/in/rcard/raise4s/Strategies.scala
core/src/test/scala/in/rcard/raise4s/StrategiesSpec.scala

Added tracing capability
